version: '3'
services:
  main:
    image: <ECR_MAIN_IMAGE_URL>
    ports:
      - '8080:3000'
    entrypoint: ['node', 'dist/src/main.js']
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=${CORS_ORIGIN}
      - ALLOW_ALL_IP=${ALLOW_ALL_IP}
      - YOUTUBE_API_KEYS=${YOUTUBE_API_KEYS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - MAX_CONCURRENT_RECORDINGS=${MAX_CONCURRENT_RECORDINGS}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_STATE=${NAVER_STATE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_MAX_RETRIES=${REDIS_MAX_RETRIES}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_RETRY_DELAY=${REDIS_RETRY_DELAY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}

  monitor:
    image: <ECR_MONITOR_IMAGE_URL>
    expose:
      - '3001'
    entrypoint: ['node', 'dist/src/monitor.js']
    environment:
      - NODE_ENV=production
      - ALLOW_ALL_IP=${ALLOW_ALL_IP}
      - YOUTUBE_API_KEYS=${YOUTUBE_API_KEYS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - MAX_CONCURRENT_RECORDINGS=${MAX_CONCURRENT_RECORDINGS}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_STATE=${NAVER_STATE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_MAX_RETRIES=${REDIS_MAX_RETRIES}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_RETRY_DELAY=${REDIS_RETRY_DELAY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}

  worker1:
    image: <ECR_WORKER1_IMAGE_URL>
    entrypoint: ['node', 'dist/src/infrastructure/recording/worker/recording.process-worker.js']
    environment:
      - WORKER_ID=worker-1
      - WORKER_PORT=5001
      - NODE_ENV=production
      - ALLOW_ALL_IP=${ALLOW_ALL_IP}
      - YOUTUBE_API_KEYS=${YOUTUBE_API_KEYS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - MAX_CONCURRENT_RECORDINGS=${MAX_CONCURRENT_RECORDINGS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_MAX_RETRIES=${REDIS_MAX_RETRIES}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_RETRY_DELAY=${REDIS_RETRY_DELAY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
  worker2:
    image: <ECR_WORKER2_IMAGE_URL>
    entrypoint: ['node', 'dist/src/infrastructure/recording/worker/recording.process-worker.js']
    environment:
      - WORKER_ID=worker-2
      - WORKER_PORT=5002
      - NODE_ENV=production
      - ALLOW_ALL_IP=${ALLOW_ALL_IP}
      - YOUTUBE_API_KEYS=${YOUTUBE_API_KEYS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - MAX_CONCURRENT_RECORDINGS=${MAX_CONCURRENT_RECORDINGS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_MAX_RETRIES=${REDIS_MAX_RETRIES}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_RETRY_DELAY=${REDIS_RETRY_DELAY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
